services:
  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun

    ports:
      - "8001:8001"
      
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=Wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Netherlands
      - VPN_PORT_FORWARDING=off
      - PORT_FORWARD_ONLY=off

    volumes:
      - ${MEDIA_DIR}/gluetun/config:/gluetun

    # Très utile pour depends_on: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8000/v1/openvpn/status"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    container_name: scraper
    depends_on:
      gluetun:
        condition: service_healthy

    # IMPORTANT: partage la pile réseau de gluetun => tout sort via VPN
    network_mode: "service:gluetun"

    environment:
      - TZ=${TZ}
      # tes variables applicatives
      - PYTHONUNBUFFERED=1

    volumes:
      - ./scraper/app:/app

    restart: unless-stopped
